version: '3.9'

x-logging-rule: &logging-rules
  logging:
    driver: "json-file"
    options:
      max-size: 20m
      max-file: "10"

networks:
  backend:
    name: backend
    external: true
    driver: bridge

services:
  database:
    image: postgres:alpine3.14
    volumes:
      - db-data:/var/lib/postgresql/data
      - db-data-dump:/docker-entrypoint-initdb.d/
    ports:
    - 5432:5432
    networks:
      - backend
    restart: unless-stopped
    <<: *logging-rules